name: First WorkFlow
on: workfow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo"Done-bye"
