name: Backmerge to Develop

on:
  push:
    branches:
      - master

jobs:
  backmerge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Backmerge to Develop
      run: |
        git checkout develope
        git merge master --no-ff
        git push origin develop
